[package]
name = "fitos-boot"
version = "0.1.0"
authors = ["Billy Stevens <contact@wasv.me>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fitos-kernel = { path = "../kernel" }

[build-dependencies]
llvm-tools = { version = "0.1" }
nasm-rs = "0.2.0"
